spring.application.name=AppEspirometrias
spring.main.web-application-type=servlet

spring.datasource.url=jdbc:postgresql://localhost:5432/appEspirometrias
spring.datasource.username=postgres
spring.datasource.password=Pandu25.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola web H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
